Timebased startrun
Minecraft-Java-Edition-Speedrunning/mcsr-serversiderng-1.16.1 pull request #13
Opened 2023-02-27 20:40 UTC by VoidXWalker

## Description
-Added an RNGInitializer Object that makes a startRun request every 30 seconds and initializes RNGHandler objects from its seed
-Client Auth now uses a file lock to not cause ratelimiting when multiple minecraft instances are used
-Refactored everything to use monads

2023-03-14 22:08 UTC, jan-leila requested changes

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/mixin/rng_verification/PlayerEntityMixin.java
> +                .orElse(random).nextInt();
```suggestion
                .orElse(random)
                .nextInt();
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/mixin/rng_verification/GeneratorOptionsMixin.java
> +            }).orElse(other);
```suggestion
            })
            .orElse(other);
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/mixin/rng_verification/AbstractTraderEntityMixin.java
> +                .orElse(random).nextInt(i);
```suggestion
                .orElse(random)
                .nextInt(i);
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/IOUtils.java
> +            String hash = zipToHash(zipFile);
I dont really like the zipping and hashing of files here being separate actions because zipToHash is completely dependent on a side effect of packZipFile. It works for now but if at some point we change the packZipFile function there could be some errors where we hash a invalid zip file. thoughts on just combining them into one zipAndHash function that does both so the ideas are more connected for future refactors?

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/IOUtils.java
> +        }
prob extract MinecraftClient.getInstance().getServer() to one var at the top

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/RNGHandler.java
> +            return Optional.of(new RNGHandler(new Random(IOUtils.getGetRandomToken(runId, ClientAuth.getInstance().orElseThrow((Supplier<Throwable>) () -> new IllegalStateException("Failed to retriev
```suggestion
            return ClientAuth.getInstance()
                .map((auth) -> new Random(IOUtils.getGetRandomToken(runId, auth).get("random").getAsLong()))
                .orElseThrow((Supplier<Throwable>) () -> new IllegalStateException("Failed to retrieve ClientAuth"));
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/RNGInitializer.java
> +        this(Optional.ofNullable(jsonObject.get("random")).orElseThrow((Supplier<Throwable>)() -> new IllegalArgumentException("Invalid JsonObject!")).getAsLong(),Optional.ofNullable(jsonObject.get("
```suggestion
        this(
            jsonObject.getAsJsonPrimitive​("random").getAsLong(),
            jsonObject.getAsJsonPrimitive​("runId").getAsLong()
        );
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/RNGInitializer.java
> +            );
```suggestion
            return ClientAuth.getInstance()
                .map((auth) -> new RNGInitializer(IOUtils.getStartRunToken(auth)))
                .orElseThrow((Supplier<Throwable>) () -> new IllegalStateException("Failed to retrieve ClientAuth"));
```

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/RNGSession.java
>              }
instead of this if else here how about put the else in `obtainedRNGHandler.orElseGet` and then put the orElseThrow after that, then just have setCurrentRNGHandler in an ifPresent

(github wont let me suggest a change over removed lines sorry :/ )

for bonus points make setCurrentRNGHandler return the handler and then just chain the next 6 lines here with it

2023-03-14 22:08 UTC, jan-leila commented on src/main/java/me/voidxwalker/serversiderng/mixin/GeneratorOptionsMixin.java
> +        }
```suggestion
        ServerSideRNG.getRNGInitializer()
            .filter(rngInitializer -> !rngInitializer.outOfTime())
            .ifPresent((initializer) -> RNGInitializer.update())
```

2023-03-18 20:39 UTC, VoidXWalker commented on src/main/java/me/voidxwalker/serversiderng/RNGInitializer.java
> +        this(Optional.ofNullable(jsonObject.get("random")).orElseThrow((Supplier<Throwable>)() -> new IllegalArgumentException("Invalid JsonObject!")).getAsLong(),Optional.ofNullable(jsonObject.get("
extra parenthesis  after "runID", typo?

2023-03-20 23:34 UTC, jan-leila approved these changes
LGTM

2023-03-22 09:32 UTC, merged